keypress("G", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("d", x, bpm)
keypress("O", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("C", x, bpm)
rest(1, bpm)
keypress("x", x, bpm)
keypress("j", x, bpm)
keypress("I", x, bpm)
rest(1.012, bpm)
keypress("C", x, bpm)
rest(1.012, bpm)
keypress("x", x, bpm)
rest(1.012, bpm)
keypress("z", x, bpm)
rest(1.012, bpm)
keypress("k", x, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
rest(2.143, bpm)
keypress("j", x, bpm)
rest(1.071, bpm)
keypress("G", x, bpm)
rest(1.071, bpm)
keypress("f", x, bpm)
keypress("a", x, bpm)
keypress("u", x, bpm)
rest(1.071, bpm)
keypress("a", x, bpm)
rest(1.071, bpm)
keypress("f", x, bpm)
rest(1.071, bpm)
keypress("G", x, bpm)
rest(1.071, bpm)
keypress("f", x, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
rest(1.65, bpm)
keypress("G", x, bpm)
rest(0.275, bpm)
keypress("f", x, bpm)
rest(0.275, bpm)
keypress("d", x, bpm)
rest(1.269, bpm)
keypress("f", x, bpm)
rest(8.12, bpm)
keypress("I", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.887, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
rest(0.887, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
rest(0.444, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("e", x, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.887, bpm)
keypress("d", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("a", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(2.661, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("^", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(2.661, bpm)
keypress("I", x, bpm)
rest(0.887, bpm)
keypress("p", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("u", x, bpm)
rest(0.887, bpm)
keypress("d", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("T", x, bpm)
rest(0.887, bpm)
keypress("a", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
rest(1.774, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
rest(0.887, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(1.774, bpm)
keypress("I", x, bpm)
rest(0.887, bpm)
keypress("p", x, bpm)
rest(0.887, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
rest(0.222, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.222, bpm)
keypress("y", x, bpm)
rest(0.222, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("r", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("E", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("E", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
rest(0.222, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.222, bpm)
keypress("y", x, bpm)
rest(0.222, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("E", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("E", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.887, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
rest(0.887, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
rest(0.444, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("e", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("e", x, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.887, bpm)
keypress("d", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("a", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(2.661, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("^", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(2.661, bpm)
keypress("I", x, bpm)
rest(0.887, bpm)
keypress("p", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("u", x, bpm)
rest(0.887, bpm)
keypress("d", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("T", x, bpm)
rest(0.887, bpm)
keypress("a", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
rest(1.774, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
rest(0.887, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(1.774, bpm)
keypress("I", x, bpm)
rest(0.887, bpm)
keypress("p", x, bpm)
rest(0.887, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
rest(0.222, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.222, bpm)
keypress("y", x, bpm)
rest(0.222, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("r", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("E", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("E", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
rest(0.222, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.222, bpm)
keypress("y", x, bpm)
rest(0.222, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("E", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("E", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.887, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.887, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("k", x, bpm)
rest(0.222, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
rest(0.222, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("h", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("h", x, bpm)
keypress("$", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.222, bpm)
keypress("j", x, bpm)
rest(0.222, bpm)
keypress("k", x, bpm)
keypress("$", x, bpm)
rest(0.222, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
rest(0.222, bpm)
keypress("x", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.17, bpm)
keypress("C", x, bpm)
rest(0.172, bpm)
keypress("x", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.07, bpm)
keypress("C", x, bpm)
rest(0.172, bpm)
keypress("x", x, bpm)
rest(0.172, bpm)
keypress("C", x, bpm)
rest(0.03, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.142, bpm)
keypress("x", x, bpm)
rest(0.172, bpm)
keypress("C", x, bpm)
rest(0.129, bpm)
keypress("7", x, bpm)
rest(0.044, bpm)
keypress("x", x, bpm)
rest(0.17, bpm)
keypress("C", x, bpm)
rest(0.229, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.17, bpm)
keypress("k", x, bpm)
rest(0.17, bpm)
keypress("j", x, bpm)
rest(0.103, bpm)
keypress("5", x, bpm)
rest(0.07, bpm)
keypress("k", x, bpm)
rest(0.17, bpm)
keypress("j", x, bpm)
rest(0.174, bpm)
keypress("k", x, bpm)
rest(0.03, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.14, bpm)
keypress("j", x, bpm)
rest(0.174, bpm)
keypress("k", x, bpm)
rest(0.129, bpm)
keypress("5", x, bpm)
rest(0.043, bpm)
keypress("j", x, bpm)
rest(0.17, bpm)
keypress("k", x, bpm)
rest(0.174, bpm)
keypress("j", x, bpm)
rest(0.057, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.113, bpm)
keypress("k", x, bpm)
rest(0.174, bpm)
keypress("j", x, bpm)
rest(0.157, bpm)
keypress("6", x, bpm)
rest(0.013, bpm)
keypress("k", x, bpm)
rest(0.174, bpm)
keypress("j", x, bpm)
rest(0.17, bpm)
keypress("k", x, bpm)
rest(0.087, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.089, bpm)
keypress("j", x, bpm)
rest(0.17, bpm)
keypress("k", x, bpm)
rest(0.17, bpm)
keypress("j", x, bpm)
rest(0.015, bpm)
keypress("6", x, bpm)
rest(0.159, bpm)
keypress("k", x, bpm)
rest(0.285, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
rest(0.222, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("u", x, bpm)
rest(0.222, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.222, bpm)
keypress("u", x, bpm)
rest(0.222, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.222, bpm)
keypress("S", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.222, bpm)
keypress("j", x, bpm)
rest(0.222, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("z", x, bpm)
rest(0.222, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.222, bpm)
keypress("C", x, bpm)
rest(0.222, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("L", x, bpm)
rest(0.222, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.17, bpm)
keypress("z", x, bpm)
rest(0.172, bpm)
keypress("L", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.07, bpm)
keypress("z", x, bpm)
rest(0.172, bpm)
keypress("L", x, bpm)
rest(0.172, bpm)
keypress("z", x, bpm)
rest(0.03, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.142, bpm)
keypress("L", x, bpm)
rest(0.172, bpm)
keypress("z", x, bpm)
rest(0.129, bpm)
keypress("7", x, bpm)
rest(0.044, bpm)
keypress("L", x, bpm)
rest(0.17, bpm)
keypress("z", x, bpm)
rest(0.229, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.065, bpm)
keypress("m", x, bpm)
rest(0.068, bpm)
keypress("n", x, bpm)
rest(0.065, bpm)
keypress("B", x, bpm)
rest(0.068, bpm)
keypress("b", x, bpm)
rest(0.065, bpm)
keypress("V", x, bpm)
rest(0.068, bpm)
keypress("v", x, bpm)
rest(0.044, bpm)
keypress("7", x, bpm)
rest(0.02, bpm)
keypress("C", x, bpm)
rest(0.068, bpm)
keypress("c", x, bpm)
rest(0.065, bpm)
keypress("x", x, bpm)
rest(0.068, bpm)
keypress("Z", x, bpm)
rest(0.065, bpm)
keypress("z", x, bpm)
rest(0.068, bpm)
keypress("L", x, bpm)
rest(0.065, bpm)
keypress("l", x, bpm)
rest(0.024, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.044, bpm)
keypress("k", x, bpm)
rest(0.065, bpm)
keypress("J", x, bpm)
rest(0.068, bpm)
keypress("j", x, bpm)
rest(0.065, bpm)
keypress("H", x, bpm)
rest(0.068, bpm)
keypress("h", x, bpm)
rest(0.065, bpm)
keypress("G", x, bpm)
rest(0.068, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("f", x, bpm)
rest(0.068, bpm)
keypress("D", x, bpm)
rest(0.065, bpm)
keypress("d", x, bpm)
rest(0.068, bpm)
keypress("S", x, bpm)
rest(0.065, bpm)
keypress("s", x, bpm)
rest(0.113, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.887, bpm)
keypress("d", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1.774, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1.774, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("3", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("3", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.887, bpm)
keypress("u", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("3", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.887, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.887, bpm)
keypress("u", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("3", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.444, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.222, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(1.996, bpm)
keypress("I", x, bpm)
rest(0.887, bpm)
keypress("p", x, bpm)
rest(0.887, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
rest(0.222, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("y", x, bpm)
rest(0.222, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("r", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("q", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("E", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.887, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
rest(0.222, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("$", x, bpm)
rest(0.222, bpm)
keypress("y", x, bpm)
rest(0.222, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("E", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("E", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.444, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.887, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.444, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
rest(0.971, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.485, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.485, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.516, bpm)
keypress("6", x, bpm)
rest(0.516, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.516, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.55, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.55, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.55, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.635, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.635, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.825, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.825, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1.031, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(2.805, bpm)
keypress("a", x, bpm)
rest(0.887, bpm)
keypress("d", x, bpm)
rest(0.887, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.887, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("L", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("L", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("z", x, bpm)
rest(0.222, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("j", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.444, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.444, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("7", x, bpm)
rest(0.222, bpm)
keypress("7", x, bpm)
rest(0.665, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.444, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.222, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)

finishedSong()