keypress("L", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("L", x, bpm)
rest(1.5, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("L", x, bpm)
rest(1.5, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("L", x, bpm)
rest(1.5, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("C", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(3, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(3, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(1.5, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(5, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(5, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(5, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(5, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(4, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(2.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(3, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(1.5, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)

finishedSong()