keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(2.5, bpm)
keypress("G", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(2.5, bpm)
keypress("G", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(2.5, bpm)
keypress("h", x, bpm)
rest(1.5, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(2.5, bpm)
keypress("h", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(1.25, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(1.25, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(1.25, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(1.25, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(1.25, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(1.25, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(1.25, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(1.25, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)

finishedSong()