keypress("7", x, bpm)
rest(2, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(4.5, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(4, bpm)
keypress("7", x, bpm)
rest(2.5, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(4.5, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(4, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(3, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(3, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("@", x, bpm)
rest(3.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(2.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(18.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(2.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(4, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(4.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(16, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(4, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(4, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(4, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(4, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(8, bpm)
keypress("5", x, bpm)
rest(8, bpm)
keypress("5", x, bpm)
rest(8, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("*", x, bpm)
rest(4.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)

finishedSong()