rest(3, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.063, bpm)
keypress("L", x, bpm)
rest(0.438, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.083, bpm)
keypress("h", x, bpm)
rest(0.083, bpm)
keypress("f", x, bpm)
rest(0.083, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.063, bpm)
keypress("L", x, bpm)
rest(0.438, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
rest(0.063, bpm)
keypress("C", x, bpm)
rest(0.438, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.083, bpm)
keypress("h", x, bpm)
rest(0.083, bpm)
keypress("f", x, bpm)
rest(0.083, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.063, bpm)
keypress("L", x, bpm)
rest(0.438, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
rest(0.063, bpm)
keypress("C", x, bpm)
rest(0.438, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.083, bpm)
keypress("h", x, bpm)
rest(0.083, bpm)
keypress("f", x, bpm)
rest(0.083, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
keypress("(", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.063, bpm)
keypress("L", x, bpm)
rest(0.438, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.083, bpm)
keypress("h", x, bpm)
rest(0.083, bpm)
keypress("f", x, bpm)
rest(0.083, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.063, bpm)
keypress("L", x, bpm)
rest(0.438, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
rest(0.063, bpm)
keypress("C", x, bpm)
rest(0.438, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.083, bpm)
keypress("h", x, bpm)
rest(0.083, bpm)
keypress("f", x, bpm)
rest(0.083, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.063, bpm)
keypress("L", x, bpm)
rest(0.438, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.083, bpm)
keypress("h", x, bpm)
rest(0.083, bpm)
keypress("f", x, bpm)
rest(0.083, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.083, bpm)
keypress("h", x, bpm)
rest(0.083, bpm)
keypress("f", x, bpm)
rest(0.083, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.063, bpm)
keypress("L", x, bpm)
rest(0.438, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.083, bpm)
keypress("h", x, bpm)
rest(0.083, bpm)
keypress("f", x, bpm)
rest(0.083, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.063, bpm)
keypress("L", x, bpm)
rest(0.438, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.063, bpm)
keypress("G", x, bpm)
rest(0.438, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.063, bpm)
keypress("L", x, bpm)
rest(0.438, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.065, bpm)
keypress("t", x, bpm)
keypress("a", x, bpm)
rest(0.435, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("2", x, bpm)
rest(0.065, bpm)
keypress("W", x, bpm)
keypress("9", x, bpm)
rest(0.067, bpm)
keypress("r", x, bpm)
rest(0.069, bpm)
keypress("T", x, bpm)
rest(1.8, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(3, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(3, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("!", x, bpm)

finishedSong()