keypress("0", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(1.5, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("7", x, bpm)
rest(3, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("!", x, bpm)
rest(0.102, bpm)
keypress("*", x, bpm)
rest(0.108, bpm)
keypress("0", x, bpm)
rest(1.29, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.108, bpm)
keypress("(", x, bpm)
rest(0.29, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(2.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.104, bpm)
keypress("%", x, bpm)
rest(0.11, bpm)
keypress("0", x, bpm)
rest(0.285, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("@", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.092, bpm)
keypress("7", x, bpm)
rest(0.094, bpm)
keypress("(", x, bpm)
rest(0.315, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(1.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.75, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.104, bpm)
keypress("7", x, bpm)
rest(0.11, bpm)
keypress("(", x, bpm)
rest(0.285, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(1.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.106, bpm)
keypress("s", x, bpm)
rest(0.108, bpm)
keypress("D", x, bpm)
rest(0.785, bpm)
keypress("%", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)

finishedSong()