keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("1", x, bpm)
rest(2, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("1", x, bpm)
rest(2, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("1", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.194, bpm)
keypress("d", x, bpm)
rest(0.806, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("2", x, bpm)
rest(0.194, bpm)
keypress("z", x, bpm)
rest(0.306, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.194, bpm)
keypress("P", x, bpm)
rest(0.306, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.194, bpm)
keypress("J", x, bpm)
rest(0.306, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.194, bpm)
keypress("d", x, bpm)
rest(0.806, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("2", x, bpm)
rest(0.194, bpm)
keypress("z", x, bpm)
rest(0.306, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(0.194, bpm)
keypress("P", x, bpm)
rest(0.306, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.194, bpm)
keypress("J", x, bpm)
rest(0.306, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.194, bpm)
keypress("d", x, bpm)
rest(0.806, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.194, bpm)
keypress("z", x, bpm)
rest(0.806, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)

finishedSong()