keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("$", x, bpm)
rest(0.2, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("$", x, bpm)
rest(0.2, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("T", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("I", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("I", x, bpm)
rest(0.2, bpm)
keypress("u", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("I", x, bpm)
rest(0.2, bpm)
keypress("u", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.7, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.2, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.8, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("I", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("T", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("I", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("I", x, bpm)
rest(0.2, bpm)
keypress("u", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.2, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("I", x, bpm)
rest(0.2, bpm)
keypress("u", x, bpm)
rest(0.071, bpm)
keypress("I", x, bpm)
rest(0.229, bpm)
keypress("I", x, bpm)
rest(0.2, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.3, bpm)
keypress("I", x, bpm)
rest(0.2, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.8, bpm)
keypress("f", x, bpm)
rest(0.2, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("S", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.45, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
rest(0.2, bpm)
keypress("S", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("G", x, bpm)
rest(0.3, bpm)
keypress("f", x, bpm)
rest(0.2, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("S", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.298, bpm)
keypress("S", x, bpm)
rest(0.702, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.8, bpm)
keypress("f", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.298, bpm)
keypress("S", x, bpm)
rest(0.702, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.8, bpm)
keypress("f", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.298, bpm)
keypress("S", x, bpm)
rest(0.702, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.8, bpm)
keypress("f", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.298, bpm)
keypress("S", x, bpm)
rest(0.702, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("f", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.8, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.3, bpm)
keypress("S", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("e", x, bpm)
rest(0.8, bpm)
keypress("f", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("H", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
rest(0.3, bpm)
keypress("k", x, bpm)
rest(0.2, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.3, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.2, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.3, bpm)
keypress("S", x, bpm)
rest(0.2, bpm)
keypress("f", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
rest(0.2, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.3, bpm)
keypress("k", x, bpm)
rest(0.2, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.083, bpm)
keypress("G", x, bpm)
rest(0.083, bpm)
keypress("f", x, bpm)
rest(0.083, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.3, bpm)
keypress("H", x, bpm)
rest(0.2, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)

finishedSong()