keypress("@", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
rest(0.108, bpm)
keypress("Y", x, bpm)
rest(0.11, bpm)
keypress("I", x, bpm)
rest(0.112, bpm)
keypress("P", x, bpm)
rest(1.669, bpm)
keypress("Z", x, bpm)
rest(0.111, bpm)
keypress("B", x, bpm)
rest(0.111, bpm)
keypress("C", x, bpm)
rest(0.111, bpm)
keypress("Z", x, bpm)
rest(0.111, bpm)
keypress("J", x, bpm)
rest(0.111, bpm)
keypress("G", x, bpm)
rest(0.111, bpm)
keypress("B", x, bpm)
rest(0.111, bpm)
keypress("C", x, bpm)
rest(0.111, bpm)
keypress("Z", x, bpm)
rest(0.111, bpm)
keypress("J", x, bpm)
rest(0.111, bpm)
keypress("G", x, bpm)
rest(0.111, bpm)
keypress("D", x, bpm)
rest(0.111, bpm)
keypress("C", x, bpm)
rest(0.111, bpm)
keypress("Z", x, bpm)
rest(0.111, bpm)
keypress("J", x, bpm)
rest(0.111, bpm)
keypress("G", x, bpm)
rest(0.111, bpm)
keypress("D", x, bpm)
rest(0.111, bpm)
keypress("P", x, bpm)
rest(0.111, bpm)
keypress("Z", x, bpm)
rest(0.111, bpm)
keypress("J", x, bpm)
rest(0.111, bpm)
keypress("G", x, bpm)
rest(0.111, bpm)
keypress("D", x, bpm)
rest(0.111, bpm)
keypress("P", x, bpm)
rest(0.111, bpm)
keypress("I", x, bpm)
rest(0.111, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.149, bpm)
keypress("Q", x, bpm)
rest(0.074, bpm)
keypress("D", x, bpm)
rest(0.074, bpm)
keypress("r", x, bpm)
rest(0.149, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
rest(0.149, bpm)
keypress("I", x, bpm)
rest(0.074, bpm)
keypress("D", x, bpm)
rest(0.074, bpm)
keypress("a", x, bpm)
rest(0.149, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(0.149, bpm)
keypress("Y", x, bpm)
rest(0.074, bpm)
keypress("a", x, bpm)
rest(0.074, bpm)
keypress("I", x, bpm)
rest(0.149, bpm)
keypress("D", x, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.167, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.111, bpm)
keypress("I", x, bpm)
rest(0.111, bpm)
keypress("a", x, bpm)
rest(0.111, bpm)
keypress("D", x, bpm)
rest(0.111, bpm)
keypress("G", x, bpm)
rest(0.111, bpm)
keypress("k", x, bpm)
rest(0.111, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.556, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.714, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.833, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.121, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.004, bpm)
keypress("^", x, bpm)
rest(0.121, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.004, bpm)
keypress("^", x, bpm)
rest(0.117, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.008, bpm)
keypress("^", x, bpm)
rest(0.117, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.008, bpm)
keypress("^", x, bpm)
rest(0.113, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.013, bpm)
keypress("^", x, bpm)
rest(0.113, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.013, bpm)
keypress("^", x, bpm)
rest(0.108, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.017, bpm)
keypress("^", x, bpm)
rest(0.108, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.017, bpm)
keypress("^", x, bpm)
rest(0.104, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.021, bpm)
keypress("^", x, bpm)
rest(0.104, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.021, bpm)
keypress("^", x, bpm)
rest(0.1, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.025, bpm)
keypress("^", x, bpm)
rest(0.1, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.025, bpm)
keypress("^", x, bpm)
rest(0.1, bpm)
keypress("^", x, bpm)
rest(0.121, bpm)
keypress("^", x, bpm)
rest(0.029, bpm)
keypress("^", x, bpm)
rest(0.096, bpm)
keypress("^", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.029, bpm)
keypress("^", x, bpm)
rest(0.096, bpm)
keypress("^", x, bpm)
rest(0.121, bpm)
keypress("^", x, bpm)
rest(0.033, bpm)
keypress("^", x, bpm)
rest(0.092, bpm)
keypress("^", x, bpm)
rest(3.492, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
rest(0.167, bpm)
keypress("C", x, bpm)
rest(0.167, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("Z", x, bpm)
rest(0.167, bpm)
keypress("C", x, bpm)
rest(0.167, bpm)
keypress("B", x, bpm)
rest(0.167, bpm)
keypress("Z", x, bpm)
rest(1.333, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.667, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.667, bpm)
keypress("!", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.667, bpm)
keypress("!", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("4", x, bpm)
rest(0.167, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.108, bpm)
keypress("J", x, bpm)
rest(0.225, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
rest(0.108, bpm)
keypress("J", x, bpm)
rest(0.225, bpm)
keypress("H", x, bpm)
rest(0.108, bpm)
keypress("J", x, bpm)
rest(0.225, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.107, bpm)
keypress("J", x, bpm)
rest(0.226, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.667, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.667, bpm)
keypress("!", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.667, bpm)
keypress("!", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.667, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.667, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.021, bpm)
keypress("G", x, bpm)
rest(0.021, bpm)
keypress("J", x, bpm)
rest(0.021, bpm)
keypress("Z", x, bpm)

finishedSong()