keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.077, bpm)
keypress("S", x, bpm)
rest(0.081, bpm)
keypress("g", x, bpm)
rest(0.842, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
rest(0.077, bpm)
keypress("S", x, bpm)
rest(0.079, bpm)
keypress("g", x, bpm)
rest(1.844, bpm)
keypress("S", x, bpm)
keypress("Y", x, bpm)
rest(0.079, bpm)
keypress("D", x, bpm)
rest(0.079, bpm)
keypress("G", x, bpm)
rest(0.342, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.257, bpm)
keypress("O", x, bpm)
rest(0.257, bpm)
keypress("S", x, bpm)
rest(0.257, bpm)
keypress("H", x, bpm)
rest(0.514, bpm)
keypress("J", x, bpm)
rest(0.257, bpm)
keypress("t", x, bpm)
rest(0.257, bpm)
keypress("O", x, bpm)
rest(0.257, bpm)
keypress("S", x, bpm)
rest(0.257, bpm)
keypress("D", x, bpm)
rest(0.514, bpm)
keypress("g", x, bpm)
rest(0.257, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
rest(0.257, bpm)
keypress("O", x, bpm)
rest(0.257, bpm)
keypress("S", x, bpm)
rest(0.257, bpm)
keypress("H", x, bpm)
rest(0.514, bpm)
keypress("g", x, bpm)
rest(0.257, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.257, bpm)
keypress("O", x, bpm)
rest(0.257, bpm)
keypress("S", x, bpm)
rest(0.257, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(0.257, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(0.257, bpm)
keypress("g", x, bpm)
rest(0.257, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
rest(0.257, bpm)
keypress("T", x, bpm)
rest(0.257, bpm)
keypress("Y", x, bpm)
rest(0.257, bpm)
keypress("O", x, bpm)
rest(0.514, bpm)
keypress("P", x, bpm)
rest(0.257, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
rest(0.257, bpm)
keypress("W", x, bpm)
rest(0.257, bpm)
keypress("T", x, bpm)
rest(0.257, bpm)
keypress("Y", x, bpm)
rest(0.514, bpm)
keypress("i", x, bpm)
rest(0.257, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("W", x, bpm)
rest(0.257, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.514, bpm)
keypress("i", x, bpm)
rest(0.257, bpm)
keypress("8", x, bpm)
rest(0.257, bpm)
keypress("W", x, bpm)
rest(0.257, bpm)
keypress("T", x, bpm)
rest(0.257, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.257, bpm)
keypress("O", x, bpm)
rest(0.257, bpm)
keypress("i", x, bpm)
rest(0.257, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.257, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(4.114, bpm)
keypress("m", x, bpm)
rest(0.257, bpm)
keypress("c", x, bpm)
rest(0.257, bpm)
keypress("Z", x, bpm)
rest(0.257, bpm)
keypress("V", x, bpm)
rest(0.257, bpm)
keypress("L", x, bpm)
rest(0.257, bpm)
keypress("l", x, bpm)
rest(0.257, bpm)
keypress("c", x, bpm)
rest(0.257, bpm)
keypress("J", x, bpm)
rest(0.257, bpm)
keypress("H", x, bpm)
rest(0.171, bpm)
keypress("Z", x, bpm)
rest(0.171, bpm)
keypress("G", x, bpm)
rest(0.171, bpm)
keypress("g", x, bpm)
rest(0.171, bpm)
keypress("l", x, bpm)
rest(0.171, bpm)
keypress("g", x, bpm)
rest(0.171, bpm)
keypress("D", x, bpm)
rest(0.206, bpm)
keypress("S", x, bpm)
rest(0.206, bpm)
keypress("s", x, bpm)
rest(0.206, bpm)
keypress("O", x, bpm)
rest(0.206, bpm)
keypress("Y", x, bpm)
rest(0.206, bpm)
keypress("T", x, bpm)
rest(2.057, bpm)
keypress("W", x, bpm)
rest(2.057, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
rest(3, bpm)
keypress("l", x, bpm)
rest(0.075, bpm)
keypress("m", x, bpm)
rest(7.919, bpm)
keypress("g", x, bpm)
keypress("O", x, bpm)
rest(0.077, bpm)
keypress("S", x, bpm)
rest(0.923, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(3.994, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("$", x, bpm)
rest(0.554, bpm)
keypress("*", x, bpm)
rest(0.554, bpm)
keypress("Q", x, bpm)
rest(0.554, bpm)
keypress("W", x, bpm)
rest(0.554, bpm)
keypress("T", x, bpm)
rest(2.215, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("$", x, bpm)
rest(0.655, bpm)
keypress("*", x, bpm)
rest(0.72, bpm)
keypress("Q", x, bpm)
rest(0.9, bpm)
keypress("W", x, bpm)
rest(1.2, bpm)
keypress("T", x, bpm)

finishedSong()