keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.375, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.375, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("4", x, bpm)
rest(0.125, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("5", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.375, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.125, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.375, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.375, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("4", x, bpm)
rest(0.125, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("5", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.375, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.375, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.375, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.375, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.375, bpm)
keypress("3", x, bpm)
rest(0.375, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.375, bpm)
keypress("$", x, bpm)
rest(0.375, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.375, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("V", x, bpm)
rest(0.125, bpm)
keypress("V", x, bpm)
rest(0.125, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("V", x, bpm)
rest(0.125, bpm)
keypress("V", x, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("V", x, bpm)
rest(0.125, bpm)
keypress("V", x, bpm)
rest(0.125, bpm)
keypress("$", x, bpm)
rest(0.375, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("3", x, bpm)
rest(0.375, bpm)
keypress("3", x, bpm)
rest(0.375, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.375, bpm)
keypress("$", x, bpm)
rest(0.375, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.375, bpm)
keypress("3", x, bpm)
rest(0.375, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.375, bpm)
keypress("7", x, bpm)
rest(0.375, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.375, bpm)
keypress("*", x, bpm)
rest(0.375, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("*", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.375, bpm)
keypress("7", x, bpm)
rest(0.375, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.375, bpm)
keypress("*", x, bpm)
rest(0.375, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("*", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.085, bpm)
keypress("O", x, bpm)
rest(0.04, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.085, bpm)
keypress("O", x, bpm)
rest(0.04, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.085, bpm)
keypress("O", x, bpm)
rest(0.04, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.375, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("*", x, bpm)
rest(0.125, bpm)
keypress("z", x, bpm)
rest(0.085, bpm)
keypress("Z", x, bpm)
rest(0.165, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("*", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.085, bpm)
keypress("O", x, bpm)
rest(0.04, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
rest(0.375, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("O", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
rest(0.375, bpm)
keypress("G", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.625, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)

finishedSong()