keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)

finishedSong()