keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(3, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(2.5, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.167, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.202, bpm)
keypress("I", x, bpm)
rest(0.298, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.501, bpm)
keypress("7", x, bpm)
rest(0.502, bpm)
keypress("0", x, bpm)
rest(0.504, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.506, bpm)
keypress("r", x, bpm)
rest(0.509, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("7", x, bpm)
rest(3.076, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(2.137, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1.068, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(3.205, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("@", x, bpm)
keypress("7", x, bpm)
rest(2.137, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1.068, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(3.205, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(2.137, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1.068, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.068, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1.068, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(1.068, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("2", x, bpm)
rest(0.534, bpm)
keypress("$", x, bpm)
rest(0.534, bpm)
keypress("6", x, bpm)
rest(0.534, bpm)
keypress("9", x, bpm)
rest(0.534, bpm)
keypress("0", x, bpm)
rest(0.534, bpm)
keypress("Q", x, bpm)
rest(0.534, bpm)
keypress("e", x, bpm)
rest(1.603, bpm)
keypress("9", x, bpm)
rest(0.534, bpm)
keypress("y", x, bpm)
rest(1.068, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(1.603, bpm)
keypress("Q", x, bpm)
keypress("*", x, bpm)
rest(0.534, bpm)
keypress("$", x, bpm)
rest(0.534, bpm)
keypress("*", x, bpm)
rest(0.534, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(1.603, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(1.603, bpm)
keypress("Q", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.603, bpm)
keypress("Q", x, bpm)
keypress("9", x, bpm)
rest(1.068, bpm)
keypress("$", x, bpm)
rest(0.534, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.534, bpm)
keypress("$", x, bpm)
rest(0.534, bpm)
keypress("*", x, bpm)
rest(0.534, bpm)
keypress("$", x, bpm)
rest(0.534, bpm)
keypress("9", x, bpm)
rest(0.534, bpm)
keypress("$", x, bpm)
rest(0.534, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("3", x, bpm)
rest(1.603, bpm)
keypress("Q", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1.603, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("!", x, bpm)
rest(1.603, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(1.603, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.521, bpm)
keypress("3", x, bpm)
rest(0.52, bpm)
keypress("$", x, bpm)
rest(0.52, bpm)
keypress("7", x, bpm)
rest(0.518, bpm)
keypress("0", x, bpm)
rest(0.516, bpm)
keypress("Q", x, bpm)
rest(0.514, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(1.02, bpm)
keypress("r", x, bpm)
rest(0.502, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.498, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.493, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(0.487, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
rest(3, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
rest(3, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("$", x, bpm)
rest(3, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
rest(3, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(3, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
rest(3, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(3, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(3, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
rest(3, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(3, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(3, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(2.5, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.167, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(2.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
rest(0.202, bpm)
keypress("G", x, bpm)
rest(0.298, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.501, bpm)
keypress("r", x, bpm)
rest(0.502, bpm)
keypress("a", x, bpm)
keypress("u", x, bpm)
rest(0.504, bpm)
keypress("r", x, bpm)
rest(0.506, bpm)
keypress("w", x, bpm)
rest(0.507, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
rest(0.509, bpm)
keypress("E", x, bpm)
rest(0.511, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.513, bpm)
keypress("I", x, bpm)
rest(0.515, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
rest(0.517, bpm)
keypress("E", x, bpm)
rest(0.519, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(3.283, bpm)
keypress("7", x, bpm)

finishedSong()