keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
rest(2, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.083, bpm)
keypress("f", x, bpm)
rest(0.083, bpm)
keypress("g", x, bpm)
rest(0.083, bpm)
keypress("h", x, bpm)
rest(0.083, bpm)
keypress("j", x, bpm)
rest(0.083, bpm)
keypress("k", x, bpm)
rest(0.083, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("u", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(0.242, bpm)
keypress("f", x, bpm)
rest(0.758, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("i", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(3, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("u", x, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(0.242, bpm)
keypress("x", x, bpm)
rest(0.244, bpm)
keypress("v", x, bpm)
rest(0.515, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(3, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(4, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.688, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.688, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.172, bpm)
keypress("s", x, bpm)
rest(0.172, bpm)
keypress("h", x, bpm)
rest(0.344, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.688, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(0.688, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.688, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.688, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.688, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.688, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.688, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.238, bpm)
keypress("k", x, bpm)
rest(0.45, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.688, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.688, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.688, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.688, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.688, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.688, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.688, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.238, bpm)
keypress("l", x, bpm)
rest(0.45, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.688, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.688, bpm)
keypress("H", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.688, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.688, bpm)
keypress("H", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.344, bpm)
keypress("B", x, bpm)
rest(0.344, bpm)
keypress("m", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
rest(0.688, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.688, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(0.688, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.688, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.688, bpm)
keypress("H", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.688, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(0.688, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.688, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.688, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.688, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.688, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.688, bpm)
keypress("J", x, bpm)
keypress("9", x, bpm)
rest(0.688, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.688, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.688, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.688, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.688, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.688, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
rest(0.688, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.688, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(0.688, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.688, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(0.688, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.688, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1.375, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.688, bpm)
keypress("6", x, bpm)
rest(0.344, bpm)
keypress("e", x, bpm)
rest(0.344, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.375, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.688, bpm)
keypress("%", x, bpm)
rest(0.344, bpm)
keypress("W", x, bpm)
rest(0.344, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(1.375, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
rest(0.688, bpm)
keypress("5", x, bpm)
rest(0.344, bpm)
keypress("w", x, bpm)
rest(0.344, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.688, bpm)
keypress("r", x, bpm)
rest(0.688, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.688, bpm)
keypress("i", x, bpm)
rest(0.688, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("r", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("w", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.344, bpm)
keypress("o", x, bpm)
rest(0.344, bpm)
keypress("Y", x, bpm)
rest(0.344, bpm)
keypress("o", x, bpm)
rest(0.344, bpm)
keypress("t", x, bpm)
rest(0.344, bpm)
keypress("o", x, bpm)
rest(0.344, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("Y", x, bpm)
rest(0.344, bpm)
keypress("o", x, bpm)
rest(0.344, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.344, bpm)
keypress("o", x, bpm)
rest(0.344, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("Y", x, bpm)
rest(0.344, bpm)
keypress("o", x, bpm)
rest(0.344, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.344, bpm)
keypress("o", x, bpm)
rest(0.344, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("Y", x, bpm)
rest(0.344, bpm)
keypress("o", x, bpm)
rest(0.344, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("r", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("w", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("d", x, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("5", x, bpm)
rest(0.344, bpm)
keypress("2", x, bpm)
rest(0.344, bpm)
keypress("5", x, bpm)
rest(0.344, bpm)
keypress("7", x, bpm)
rest(0.344, bpm)
keypress("9", x, bpm)
rest(0.344, bpm)
keypress("w", x, bpm)
rest(0.344, bpm)
keypress("r", x, bpm)
rest(0.344, bpm)
keypress("y", x, bpm)
rest(0.344, bpm)
keypress("o", x, bpm)
rest(0.344, bpm)
keypress("a", x, bpm)
rest(0.344, bpm)
keypress("d", x, bpm)
rest(0.344, bpm)
keypress("h", x, bpm)
rest(0.344, bpm)
keypress("k", x, bpm)
rest(0.344, bpm)
keypress("z", x, bpm)
rest(0.344, bpm)
keypress("v", x, bpm)
rest(0.344, bpm)
keypress("n", x, bpm)
rest(5.844, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.242, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.244, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(1.515, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
keypress("7", x, bpm)
rest(0.667, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("o", x, bpm)
keypress("%", x, bpm)
rest(0.121, bpm)
keypress("(", x, bpm)
rest(0.121, bpm)
keypress("W", x, bpm)
rest(0.123, bpm)
keypress("t", x, bpm)
rest(0.635, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.242, bpm)
keypress("8", x, bpm)
rest(0.244, bpm)
keypress("q", x, bpm)
rest(0.246, bpm)
keypress("W", x, bpm)
rest(1.269, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.242, bpm)
keypress("q", x, bpm)
rest(0.244, bpm)
keypress("E", x, bpm)
rest(1.515, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.667, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
rest(0.667, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
rest(0.667, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(2, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.667, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.667, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("k", x, bpm)
rest(0.667, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.667, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("l", x, bpm)
rest(0.667, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("Z", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.667, bpm)
keypress("g", x, bpm)
rest(0.667, bpm)
keypress("h", x, bpm)
rest(0.667, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("k", x, bpm)
rest(0.667, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.667, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.667, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.667, bpm)
keypress("g", x, bpm)
rest(0.667, bpm)
keypress("h", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.667, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.667, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.667, bpm)
keypress("t", x, bpm)
keypress("5", x, bpm)
rest(0.667, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.667, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.667, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.667, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.667, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("k", x, bpm)
rest(0.667, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
rest(0.667, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("Z", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("k", x, bpm)
rest(0.667, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("D", x, bpm)
rest(0.667, bpm)
keypress("g", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("q", x, bpm)
rest(0.667, bpm)
keypress("(", x, bpm)
rest(0.667, bpm)
keypress("9", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.667, bpm)
keypress("g", x, bpm)
rest(0.667, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.667, bpm)
keypress("8", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.667, bpm)
keypress("w", x, bpm)
rest(0.667, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("Y", x, bpm)
rest(0.667, bpm)
keypress("o", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
rest(0.667, bpm)
keypress("D", x, bpm)
rest(0.667, bpm)
keypress("h", x, bpm)
rest(0.667, bpm)
keypress("l", x, bpm)
rest(0.667, bpm)
keypress("z", x, bpm)
rest(0.667, bpm)
keypress("Z", x, bpm)
rest(0.667, bpm)
keypress("l", x, bpm)
rest(0.24, bpm)
keypress("Z", x, bpm)
rest(0.244, bpm)
keypress("v", x, bpm)
rest(3.517, bpm)
keypress("8", x, bpm)

finishedSong()