keypress("6", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("*", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("8", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("u", x, bpm)
rest(4.897, bpm)
keypress("6", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("*", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("9", x, bpm)
rest(0.6, bpm)
keypress("Q", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.4, bpm)
keypress("O", x, bpm)
rest(0.6, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.4, bpm)
keypress("r", x, bpm)
rest(0.6, bpm)
keypress("e", x, bpm)
rest(0.4, bpm)
keypress("6", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("*", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("8", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.4, bpm)
keypress("r", x, bpm)
rest(0.6, bpm)
keypress("e", x, bpm)
rest(0.4, bpm)
keypress("8", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.4, bpm)
keypress("0", x, bpm)
rest(0.6, bpm)
keypress("e", x, bpm)
rest(0.4, bpm)
keypress("6", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("u", x, bpm)
rest(0.4, bpm)
keypress("*", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.4, bpm)
keypress("T", x, bpm)
rest(0.6, bpm)
keypress("e", x, bpm)
rest(0.4, bpm)
keypress("8", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("7", x, bpm)
rest(0.986, bpm)
keypress("e", x, bpm)
rest(0.657, bpm)
keypress("r", x, bpm)
rest(0.821, bpm)
keypress("e", x, bpm)
rest(0.041, bpm)
keypress("y", x, bpm)
rest(0.044, bpm)
keypress("u", x, bpm)
rest(0.079, bpm)
keypress("3", x, bpm)
rest(5.584, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.575, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.383, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.575, bpm)
keypress("W", x, bpm)
rest(0.383, bpm)
keypress("r", x, bpm)
rest(0.575, bpm)
keypress("u", x, bpm)
rest(0.958, bpm)
keypress("r", x, bpm)
rest(0.383, bpm)
keypress("W", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.958, bpm)
keypress("w", x, bpm)
rest(0.575, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.958, bpm)
keypress("w", x, bpm)
rest(0.383, bpm)
keypress("8", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
rest(0.575, bpm)
keypress("Q", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("r", x, bpm)
rest(0.383, bpm)
keypress("0", x, bpm)
rest(0.575, bpm)
keypress("3", x, bpm)
rest(0.383, bpm)
keypress("7", x, bpm)
rest(0.575, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.575, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
rest(0.122, bpm)
keypress("f", x, bpm)
rest(0.837, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.383, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.958, bpm)
keypress("w", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.958, bpm)
keypress("r", x, bpm)
rest(0.575, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.958, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("T", x, bpm)
rest(0.383, bpm)
keypress("r", x, bpm)
rest(0.575, bpm)
keypress("e", x, bpm)
rest(0.383, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.575, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.383, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.575, bpm)
keypress("W", x, bpm)
rest(0.383, bpm)
keypress("r", x, bpm)
rest(0.575, bpm)
keypress("u", x, bpm)
rest(0.958, bpm)
keypress("r", x, bpm)
rest(0.383, bpm)
keypress("W", x, bpm)
rest(0.575, bpm)
keypress("*", x, bpm)
rest(0.383, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.575, bpm)
keypress("w", x, bpm)
rest(0.383, bpm)
keypress("t", x, bpm)
rest(0.575, bpm)
keypress("f", x, bpm)
rest(0.958, bpm)
keypress("t", x, bpm)
rest(0.383, bpm)
keypress("w", x, bpm)
rest(0.575, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
rest(0.958, bpm)
keypress("Q", x, bpm)
rest(0.383, bpm)
keypress("r", x, bpm)
rest(0.575, bpm)
keypress("u", x, bpm)
rest(0.958, bpm)
keypress("3", x, bpm)
rest(0.383, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.575, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
rest(0.575, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("6", x, bpm)
rest(0.958, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
rest(0.958, bpm)
keypress("*", x, bpm)
rest(0.958, bpm)
keypress("G", x, bpm)
rest(0.958, bpm)
keypress("*", x, bpm)
rest(0.124, bpm)
keypress("!", x, bpm)
rest(0.835, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.479, bpm)
keypress("p", x, bpm)
rest(0.479, bpm)
keypress("f", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("9", x, bpm)
rest(1.533, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.958, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("T", x, bpm)
rest(0.383, bpm)
keypress("r", x, bpm)
rest(0.575, bpm)
keypress("e", x, bpm)
rest(0.383, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.958, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("O", x, bpm)
keypress("9", x, bpm)
rest(0.575, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(1.342, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.639, bpm)
keypress("h", x, bpm)
rest(0.319, bpm)
keypress("e", x, bpm)
rest(0.319, bpm)
keypress("G", x, bpm)
rest(0.639, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.958, bpm)
keypress("w", x, bpm)
rest(0.958, bpm)
keypress("8", x, bpm)
rest(0.575, bpm)
keypress("w", x, bpm)
rest(1.342, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.958, bpm)
keypress("Q", x, bpm)
rest(0.958, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.958, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.575, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(1.342, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.958, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
rest(1.917, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.126, bpm)
keypress("T", x, bpm)
rest(0.833, bpm)
keypress("p", x, bpm)
rest(0.958, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.958, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("O", x, bpm)
keypress("9", x, bpm)
rest(0.575, bpm)
keypress("p", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("a", x, bpm)
rest(0.383, bpm)
keypress("*", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.639, bpm)
keypress("h", x, bpm)
rest(0.319, bpm)
keypress("e", x, bpm)
rest(0.319, bpm)
keypress("G", x, bpm)
rest(0.639, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("8", x, bpm)
rest(0.575, bpm)
keypress("e", x, bpm)
rest(1.342, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.126, bpm)
keypress("e", x, bpm)
rest(1.791, bpm)
keypress("f", x, bpm)
rest(0.958, bpm)
keypress("S", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.126, bpm)
keypress("r", x, bpm)
rest(0.833, bpm)
keypress("p", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
rest(0.958, bpm)
keypress("S", x, bpm)
rest(0.958, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.126, bpm)
keypress("T", x, bpm)
rest(1.791, bpm)
keypress("a", x, bpm)
rest(1.917, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.126, bpm)
keypress("T", x, bpm)
rest(0.833, bpm)
keypress("p", x, bpm)
rest(0.958, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.084, bpm)
keypress("e", x, bpm)
rest(5.666, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
rest(0.958, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
rest(0.084, bpm)
keypress("e", x, bpm)
rest(5.666, bpm)
keypress("r", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.958, bpm)
keypress("T", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.126, bpm)
keypress("Q", x, bpm)
rest(3.708, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(3.833, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(4.929, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(3.286, bpm)
keypress("e", x, bpm)
keypress("3", x, bpm)
rest(0.12, bpm)
keypress("0", x, bpm)
rest(6.04, bpm)
keypress("6", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("*", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("8", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("u", x, bpm)
rest(4.897, bpm)
keypress("6", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("*", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("9", x, bpm)
rest(0.6, bpm)
keypress("Q", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.4, bpm)
keypress("O", x, bpm)
rest(0.6, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.4, bpm)
keypress("r", x, bpm)
rest(0.6, bpm)
keypress("e", x, bpm)
rest(0.4, bpm)
keypress("6", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("*", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("8", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.4, bpm)
keypress("r", x, bpm)
rest(0.6, bpm)
keypress("e", x, bpm)
rest(0.4, bpm)
keypress("8", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.4, bpm)
keypress("0", x, bpm)
rest(0.6, bpm)
keypress("e", x, bpm)
rest(0.4, bpm)
keypress("6", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("u", x, bpm)
rest(0.4, bpm)
keypress("*", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.4, bpm)
keypress("T", x, bpm)
rest(0.6, bpm)
keypress("e", x, bpm)
rest(0.4, bpm)
keypress("8", x, bpm)
rest(0.6, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.4, bpm)
keypress("e", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("7", x, bpm)
rest(0.986, bpm)
keypress("e", x, bpm)
rest(0.657, bpm)
keypress("r", x, bpm)
rest(0.821, bpm)
keypress("e", x, bpm)
rest(0.041, bpm)
keypress("y", x, bpm)
rest(0.044, bpm)
keypress("u", x, bpm)
rest(0.079, bpm)
keypress("3", x, bpm)
rest(5.584, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.575, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.383, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.575, bpm)
keypress("W", x, bpm)
rest(0.383, bpm)
keypress("r", x, bpm)
rest(0.575, bpm)
keypress("u", x, bpm)
rest(0.958, bpm)
keypress("r", x, bpm)
rest(0.383, bpm)
keypress("W", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.958, bpm)
keypress("w", x, bpm)
rest(0.575, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.958, bpm)
keypress("w", x, bpm)
rest(0.383, bpm)
keypress("8", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
rest(0.575, bpm)
keypress("Q", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("r", x, bpm)
rest(0.383, bpm)
keypress("0", x, bpm)
rest(0.575, bpm)
keypress("3", x, bpm)
rest(0.383, bpm)
keypress("7", x, bpm)
rest(0.575, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.575, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
rest(0.122, bpm)
keypress("f", x, bpm)
rest(0.837, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.383, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.958, bpm)
keypress("w", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.958, bpm)
keypress("r", x, bpm)
rest(0.575, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.958, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("T", x, bpm)
rest(0.383, bpm)
keypress("r", x, bpm)
rest(0.575, bpm)
keypress("e", x, bpm)
rest(0.383, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.575, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.383, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.575, bpm)
keypress("W", x, bpm)
rest(0.383, bpm)
keypress("r", x, bpm)
rest(0.575, bpm)
keypress("u", x, bpm)
rest(0.958, bpm)
keypress("r", x, bpm)
rest(0.383, bpm)
keypress("W", x, bpm)
rest(0.575, bpm)
keypress("*", x, bpm)
rest(0.383, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.575, bpm)
keypress("w", x, bpm)
rest(0.383, bpm)
keypress("t", x, bpm)
rest(0.575, bpm)
keypress("f", x, bpm)
rest(0.958, bpm)
keypress("t", x, bpm)
rest(0.383, bpm)
keypress("w", x, bpm)
rest(0.575, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
rest(0.958, bpm)
keypress("Q", x, bpm)
rest(0.383, bpm)
keypress("r", x, bpm)
rest(0.575, bpm)
keypress("u", x, bpm)
rest(0.958, bpm)
keypress("3", x, bpm)
rest(0.383, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.575, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
rest(0.575, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("6", x, bpm)
rest(0.958, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
rest(0.958, bpm)
keypress("*", x, bpm)
rest(0.958, bpm)
keypress("G", x, bpm)
rest(0.958, bpm)
keypress("*", x, bpm)
rest(0.124, bpm)
keypress("!", x, bpm)
rest(0.835, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.479, bpm)
keypress("p", x, bpm)
rest(0.479, bpm)
keypress("f", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("9", x, bpm)
rest(1.533, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.958, bpm)
keypress("0", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("T", x, bpm)
rest(0.383, bpm)
keypress("r", x, bpm)
rest(0.575, bpm)
keypress("e", x, bpm)
rest(0.383, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.958, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("O", x, bpm)
keypress("9", x, bpm)
rest(0.575, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(1.342, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.639, bpm)
keypress("h", x, bpm)
rest(0.319, bpm)
keypress("e", x, bpm)
rest(0.319, bpm)
keypress("G", x, bpm)
rest(0.639, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.958, bpm)
keypress("w", x, bpm)
rest(0.958, bpm)
keypress("8", x, bpm)
rest(0.575, bpm)
keypress("w", x, bpm)
rest(1.342, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.958, bpm)
keypress("Q", x, bpm)
rest(0.958, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.958, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.575, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(1.342, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.958, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
rest(1.917, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.126, bpm)
keypress("T", x, bpm)
rest(0.833, bpm)
keypress("p", x, bpm)
rest(0.958, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.958, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("O", x, bpm)
keypress("9", x, bpm)
rest(0.575, bpm)
keypress("p", x, bpm)
rest(0.383, bpm)
keypress("e", x, bpm)
rest(0.575, bpm)
keypress("a", x, bpm)
rest(0.383, bpm)
keypress("*", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.639, bpm)
keypress("h", x, bpm)
rest(0.319, bpm)
keypress("e", x, bpm)
rest(0.319, bpm)
keypress("G", x, bpm)
rest(0.639, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
rest(0.958, bpm)
keypress("8", x, bpm)
rest(0.575, bpm)
keypress("e", x, bpm)
rest(1.342, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.126, bpm)
keypress("e", x, bpm)
rest(1.791, bpm)
keypress("f", x, bpm)
rest(0.958, bpm)
keypress("S", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.126, bpm)
keypress("r", x, bpm)
rest(0.833, bpm)
keypress("p", x, bpm)
rest(0.958, bpm)
keypress("a", x, bpm)
rest(0.958, bpm)
keypress("S", x, bpm)
rest(0.958, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.126, bpm)
keypress("T", x, bpm)
rest(1.791, bpm)
keypress("a", x, bpm)
rest(1.917, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.126, bpm)
keypress("T", x, bpm)
rest(0.833, bpm)
keypress("p", x, bpm)
rest(0.958, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("p", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.084, bpm)
keypress("e", x, bpm)
rest(5.666, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.958, bpm)
keypress("u", x, bpm)
rest(0.958, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
rest(0.084, bpm)
keypress("e", x, bpm)
rest(5.666, bpm)
keypress("r", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.958, bpm)
keypress("T", x, bpm)
rest(0.958, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.126, bpm)
keypress("Q", x, bpm)
rest(3.708, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(3.833, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(4.929, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(3.286, bpm)
keypress("e", x, bpm)
keypress("3", x, bpm)
rest(0.12, bpm)
keypress("0", x, bpm)

finishedSong()