keypress("8", x, bpm)
rest(0.075, bpm)
keypress("(", x, bpm)
rest(0.075, bpm)
keypress("w", x, bpm)
rest(0.077, bpm)
keypress("E", x, bpm)
rest(7.773, bpm)
keypress("5", x, bpm)
rest(0.075, bpm)
keypress("^", x, bpm)
rest(0.075, bpm)
keypress("9", x, bpm)
rest(0.077, bpm)
keypress("q", x, bpm)
rest(7.773, bpm)
keypress("^", x, bpm)
rest(0.075, bpm)
keypress("*", x, bpm)
rest(0.075, bpm)
keypress("q", x, bpm)
rest(0.077, bpm)
keypress("W", x, bpm)
rest(7.773, bpm)
keypress("4", x, bpm)
rest(0.075, bpm)
keypress("%", x, bpm)
rest(0.075, bpm)
keypress("8", x, bpm)
rest(0.077, bpm)
keypress("(", x, bpm)
rest(7.773, bpm)
keypress("8", x, bpm)
rest(0.063, bpm)
keypress("(", x, bpm)
rest(0.069, bpm)
keypress("w", x, bpm)
rest(0.069, bpm)
keypress("E", x, bpm)
rest(0.8, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.063, bpm)
keypress("^", x, bpm)
rest(0.069, bpm)
keypress("9", x, bpm)
rest(0.069, bpm)
keypress("q", x, bpm)
rest(0.8, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(2.5, bpm)
keypress("^", x, bpm)
rest(0.063, bpm)
keypress("*", x, bpm)
rest(0.069, bpm)
keypress("q", x, bpm)
rest(0.069, bpm)
keypress("W", x, bpm)
rest(0.8, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.063, bpm)
keypress("%", x, bpm)
rest(0.069, bpm)
keypress("8", x, bpm)
rest(0.069, bpm)
keypress("(", x, bpm)
rest(1.3, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(4.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.131, bpm)
keypress("D", x, bpm)
rest(0.133, bpm)
keypress("h", x, bpm)
rest(0.135, bpm)
keypress("J", x, bpm)
rest(0.6, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.131, bpm)
keypress("P", x, bpm)
rest(0.133, bpm)
keypress("d", x, bpm)
rest(0.135, bpm)
keypress("g", x, bpm)
rest(0.6, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.131, bpm)
keypress("S", x, bpm)
rest(0.133, bpm)
keypress("g", x, bpm)
rest(0.135, bpm)
keypress("H", x, bpm)
rest(0.6, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.131, bpm)
keypress("D", x, bpm)
rest(0.133, bpm)
keypress("h", x, bpm)
rest(0.135, bpm)
keypress("J", x, bpm)
rest(0.6, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.131, bpm)
keypress("P", x, bpm)
rest(0.133, bpm)
keypress("d", x, bpm)
rest(0.135, bpm)
keypress("g", x, bpm)
rest(0.6, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.131, bpm)
keypress("S", x, bpm)
rest(0.133, bpm)
keypress("g", x, bpm)
rest(0.135, bpm)
keypress("H", x, bpm)
rest(0.6, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.131, bpm)
keypress("D", x, bpm)
rest(0.133, bpm)
keypress("h", x, bpm)
rest(0.135, bpm)
keypress("J", x, bpm)
rest(0.6, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.131, bpm)
keypress("S", x, bpm)
rest(0.133, bpm)
keypress("g", x, bpm)
rest(0.135, bpm)
keypress("H", x, bpm)
rest(0.6, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("G", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.131, bpm)
keypress("O", x, bpm)
rest(0.133, bpm)
keypress("s", x, bpm)
rest(0.133, bpm)
keypress("D", x, bpm)
rest(1.102, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.131, bpm)
keypress("(", x, bpm)
rest(0.131, bpm)
keypress("Q", x, bpm)
rest(1.738, bpm)
keypress("l", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
rest(0.667, bpm)
keypress("h", x, bpm)
rest(0.667, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.131, bpm)
keypress("7", x, bpm)
rest(0.131, bpm)
keypress("9", x, bpm)
rest(0.738, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.131, bpm)
keypress("%", x, bpm)
rest(0.131, bpm)
keypress("*", x, bpm)
rest(1.738, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("l", x, bpm)
rest(0.75, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
rest(0.131, bpm)
keypress("8", x, bpm)
rest(0.131, bpm)
keypress("(", x, bpm)
rest(2.738, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.131, bpm)
keypress("9", x, bpm)
rest(0.131, bpm)
keypress("q", x, bpm)
rest(0.138, bpm)
keypress("W", x, bpm)
rest(3.6, bpm)
keypress("^", x, bpm)
rest(0.131, bpm)
keypress("9", x, bpm)
rest(0.131, bpm)
keypress("q", x, bpm)
rest(0.138, bpm)
keypress("W", x, bpm)
rest(3.6, bpm)
keypress("^", x, bpm)
rest(0.131, bpm)
keypress("*", x, bpm)
rest(0.131, bpm)
keypress("0", x, bpm)
rest(0.138, bpm)
keypress("w", x, bpm)
rest(3.6, bpm)
keypress("^", x, bpm)
rest(0.131, bpm)
keypress("*", x, bpm)
rest(0.131, bpm)
keypress("0", x, bpm)
rest(0.138, bpm)
keypress("w", x, bpm)
rest(3.6, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.131, bpm)
keypress("D", x, bpm)
rest(0.133, bpm)
keypress("h", x, bpm)
rest(0.135, bpm)
keypress("J", x, bpm)
rest(0.6, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.131, bpm)
keypress("P", x, bpm)
rest(0.133, bpm)
keypress("d", x, bpm)
rest(0.135, bpm)
keypress("g", x, bpm)
rest(0.6, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.131, bpm)
keypress("S", x, bpm)
rest(0.133, bpm)
keypress("g", x, bpm)
rest(0.135, bpm)
keypress("H", x, bpm)
rest(0.6, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.131, bpm)
keypress("D", x, bpm)
rest(0.133, bpm)
keypress("h", x, bpm)
rest(0.135, bpm)
keypress("J", x, bpm)
rest(0.6, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.131, bpm)
keypress("P", x, bpm)
rest(0.133, bpm)
keypress("d", x, bpm)
rest(0.135, bpm)
keypress("g", x, bpm)
rest(0.6, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.131, bpm)
keypress("S", x, bpm)
rest(0.133, bpm)
keypress("g", x, bpm)
rest(0.135, bpm)
keypress("H", x, bpm)
rest(0.6, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.083, bpm)
keypress("g", x, bpm)
rest(0.083, bpm)
keypress("l", x, bpm)

finishedSong()