keypress("q", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.75, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.75, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.517, bpm)
keypress("4", x, bpm)
keypress("W", x, bpm)
rest(0.533, bpm)
keypress("4", x, bpm)
keypress("E", x, bpm)
rest(0.533, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.533, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.571, bpm)
keypress("4", x, bpm)
keypress("W", x, bpm)
rest(0.571, bpm)
keypress("4", x, bpm)
keypress("E", x, bpm)
rest(0.571, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.593, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.615, bpm)
keypress("4", x, bpm)
keypress("W", x, bpm)
rest(0.615, bpm)
keypress("4", x, bpm)
keypress("E", x, bpm)
rest(0.615, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("9", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("(", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.375, bpm)
keypress("(", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(1.125, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("9", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1.125, bpm)
keypress("(", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.375, bpm)
keypress("(", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("9", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("(", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("E", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("(", x, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("w", x, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("w", x, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("w", x, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.375, bpm)
keypress("(", x, bpm)
rest(0.375, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("9", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("(", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("E", x, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("1", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)

finishedSong()