keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
rest(0.131, bpm)
keypress("C", x, bpm)
rest(0.869, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(0.131, bpm)
keypress("n", x, bpm)
rest(0.869, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("C", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("Z", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("u", x, bpm)
rest(0.131, bpm)
keypress("k", x, bpm)
rest(0.133, bpm)
keypress("x", x, bpm)
rest(0.735, bpm)
keypress("Z", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.131, bpm)
keypress("k", x, bpm)
rest(0.133, bpm)
keypress("C", x, bpm)
rest(0.735, bpm)
keypress("L", x, bpm)
rest(0.131, bpm)
keypress("Z", x, bpm)
rest(0.869, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
rest(2, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("E", x, bpm)
keypress("O", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("x", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Z", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("x", x, bpm)
keypress("Q", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("Z", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("!", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
rest(2, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(1.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("a", x, bpm)
rest(2, bpm)
keypress("C", x, bpm)
rest(2, bpm)
keypress("L", x, bpm)
keypress("P", x, bpm)
rest(4, bpm)
keypress("k", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("C", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("O", x, bpm)
rest(4, bpm)
keypress("L", x, bpm)
keypress("y", x, bpm)
rest(4, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(4, bpm)
keypress("k", x, bpm)
keypress("t", x, bpm)

finishedSong()