keypress("Q", x, bpm)
keypress("@", x, bpm)
rest(0.75, bpm)
keypress("Q", x, bpm)
keypress("@", x, bpm)
rest(0.75, bpm)
keypress("Q", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("Q", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("Q", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("i", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("L", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)

finishedSong()