keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(1.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.196, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.804, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)

finishedSong()