keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1.033, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1.067, bpm)
keypress("Q", x, bpm)
rest(1.143, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1.187, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(2.996, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(1.087, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1.087, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.815, bpm)
keypress("g", x, bpm)
rest(0.272, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(1.087, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1.087, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.815, bpm)
keypress("S", x, bpm)
rest(0.272, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.815, bpm)
keypress("g", x, bpm)
rest(0.272, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.815, bpm)
keypress("S", x, bpm)
rest(0.272, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(1.087, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1.087, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.815, bpm)
keypress("S", x, bpm)
rest(0.272, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(1.087, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1.087, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.815, bpm)
keypress("G", x, bpm)
rest(0.272, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(1.087, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.123, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.159, bpm)
keypress("7", x, bpm)
rest(1.242, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2.842, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(1.087, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1.087, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.815, bpm)
keypress("g", x, bpm)
rest(0.272, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(1.087, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1.087, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.815, bpm)
keypress("S", x, bpm)
rest(0.272, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.815, bpm)
keypress("g", x, bpm)
rest(0.272, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.815, bpm)
keypress("S", x, bpm)
rest(0.272, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(1.087, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1.087, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.815, bpm)
keypress("G", x, bpm)
rest(0.272, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(1.087, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1.087, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1.087, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.087, bpm)
keypress("7", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(3.256, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(1.087, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1.087, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1.087, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(1.087, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1.087, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1.087, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(1.087, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1.087, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1.087, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.123, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.159, bpm)
keypress("7", x, bpm)
rest(1.242, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.29, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(3.256, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(1.087, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1.087, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.815, bpm)
keypress("g", x, bpm)
rest(0.272, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(1.087, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1.087, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.815, bpm)
keypress("S", x, bpm)
rest(0.272, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.815, bpm)
keypress("g", x, bpm)
rest(0.272, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.087, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.815, bpm)
keypress("S", x, bpm)
rest(0.272, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(1.087, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1.087, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.815, bpm)
keypress("G", x, bpm)
rest(0.272, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(1.087, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1.087, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1.203, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(1.242, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.346, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.449, bpm)
keypress("7", x, bpm)
rest(1.522, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)

finishedSong()