keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("1", x, bpm)
rest(0.667, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("5", x, bpm)
rest(0.667, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.667, bpm)
keypress("h", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("1", x, bpm)
rest(0.667, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("5", x, bpm)
rest(0.667, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.667, bpm)
keypress("h", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.167, bpm)
keypress("5", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1.75, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.167, bpm)
keypress("4", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("w", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.167, bpm)
keypress("5", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("1", x, bpm)
rest(0.667, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("5", x, bpm)
rest(0.667, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.667, bpm)
keypress("h", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("1", x, bpm)
rest(0.667, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("5", x, bpm)
rest(0.667, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.667, bpm)
keypress("h", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)

finishedSong()