keypress("e", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.054, bpm)
keypress("Q", x, bpm)
rest(0.054, bpm)
keypress("e", x, bpm)
rest(2.642, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(3, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(3, bpm)
keypress("a", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(2.75, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("r", x, bpm)
rest(3, bpm)
keypress("w", x, bpm)
keypress("6", x, bpm)
rest(0.133, bpm)
keypress("0", x, bpm)
rest(0.002, bpm)
keypress("e", x, bpm)
rest(0.138, bpm)
keypress("e", x, bpm)
rest(0.002, bpm)
keypress("u", x, bpm)
rest(1.725, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.054, bpm)
keypress("Q", x, bpm)
rest(0.054, bpm)
keypress("e", x, bpm)
rest(2.642, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(3, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(3, bpm)
keypress("a", x, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(2.75, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.667, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.667, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
rest(0.667, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
rest(0.667, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.667, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.667, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
rest(0.667, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
rest(0.667, bpm)
keypress("d", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
rest(0.667, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.133, bpm)
keypress("e", x, bpm)
rest(0.14, bpm)
keypress("u", x, bpm)
rest(2.727, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.054, bpm)
keypress("Q", x, bpm)
rest(0.054, bpm)
keypress("e", x, bpm)
rest(2.642, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(3, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(3, bpm)
keypress("a", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(2.75, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("r", x, bpm)
rest(3, bpm)
keypress("w", x, bpm)
keypress("6", x, bpm)
rest(0.133, bpm)
keypress("0", x, bpm)
rest(0.002, bpm)
keypress("e", x, bpm)
rest(0.138, bpm)
keypress("e", x, bpm)
rest(0.002, bpm)
keypress("u", x, bpm)
rest(1.725, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.054, bpm)
keypress("Q", x, bpm)
rest(0.054, bpm)
keypress("e", x, bpm)
rest(2.642, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(3, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(3, bpm)
keypress("a", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(2.75, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.033, bpm)
keypress("Q", x, bpm)
rest(0.033, bpm)
keypress("e", x, bpm)

finishedSong()