rest(3, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("1", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(4, bpm)
keypress("3", x, bpm)
rest(4, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
rest(0.131, bpm)
keypress("e", x, bpm)
rest(0.133, bpm)
keypress("t", x, bpm)
rest(1.735, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.131, bpm)
keypress("w", x, bpm)
rest(0.133, bpm)
keypress("r", x, bpm)
rest(1.735, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(2, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.131, bpm)
keypress("r", x, bpm)
rest(0.133, bpm)
keypress("y", x, bpm)
rest(0.485, bpm)
keypress("h", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.131, bpm)
keypress("0", x, bpm)
rest(0.133, bpm)
keypress("e", x, bpm)
rest(0.235, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(1.5, bpm)
keypress("j", x, bpm)
keypress("(", x, bpm)
rest(0.131, bpm)
keypress("Q", x, bpm)
rest(0.133, bpm)
keypress("e", x, bpm)
rest(1.235, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.013, bpm)
keypress("Q", x, bpm)
rest(0.017, bpm)
keypress("r", x, bpm)
rest(2.971, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(2.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(3, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(2.5, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(4.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(4, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("3", x, bpm)
rest(2.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(6, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("z", x, bpm)
rest(0.125, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.75, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("v", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(2.5, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(2.5, bpm)
keypress("z", x, bpm)
keypress("v", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
keypress("B", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("L", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("L", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("L", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.806, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.906, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.604, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.989, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(1.087, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
rest(0.806, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(6.444, bpm)
keypress("4", x, bpm)

finishedSong()