keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("7", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("v", x, bpm)
keypress("2", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)

finishedSong()