rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(3.75, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
keypress("j", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(4.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(3.75, bpm)
keypress("9", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("e", x, bpm)
rest(2.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)

finishedSong()