keypress("i", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(3, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
keypress("a", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("%", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("(", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(6, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(15, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(9, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)

finishedSong()