keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.7, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.3, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.7, bpm)
keypress("f", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.075, bpm)
keypress("g", x, bpm)
rest(0.258, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(0.7, bpm)
keypress("D", x, bpm)
rest(0.3, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("D", x, bpm)
rest(0.075, bpm)
keypress("g", x, bpm)
rest(0.258, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.667, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.075, bpm)
keypress("D", x, bpm)
rest(0.925, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("Z", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
keypress("*", x, bpm)
rest(0.7, bpm)
keypress("Z", x, bpm)
rest(0.3, bpm)
keypress("l", x, bpm)
rest(0.7, bpm)
keypress("c", x, bpm)
rest(0.3, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("$", x, bpm)
rest(0.7, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.3, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.7, bpm)
keypress("f", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.7, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.3, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("!", x, bpm)
rest(0.7, bpm)
keypress("D", x, bpm)
rest(0.3, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("D", x, bpm)
rest(0.075, bpm)
keypress("g", x, bpm)
rest(0.258, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(1.333, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("$", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
rest(0.11, bpm)
keypress("L", x, bpm)
rest(0.112, bpm)
keypress("L", x, bpm)
rest(0.11, bpm)
keypress("L", x, bpm)
rest(0.11, bpm)
keypress("L", x, bpm)
rest(0.113, bpm)
keypress("L", x, bpm)
rest(0.11, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(0.7, bpm)
keypress("D", x, bpm)
rest(0.3, bpm)
keypress("s", x, bpm)
rest(0.667, bpm)
keypress("D", x, bpm)
rest(0.075, bpm)
keypress("g", x, bpm)
rest(0.258, bpm)
keypress("P", x, bpm)
rest(2, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("C", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.075, bpm)
keypress("v", x, bpm)
rest(0.925, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.7, bpm)
keypress("l", x, bpm)
rest(0.3, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("Z", x, bpm)
rest(0.333, bpm)
keypress("C", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.075, bpm)
keypress("v", x, bpm)
rest(0.925, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.7, bpm)
keypress("c", x, bpm)
rest(0.3, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("c", x, bpm)
rest(0.667, bpm)
keypress("c", x, bpm)
keypress("1", x, bpm)
rest(2, bpm)
keypress("x", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.7, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
rest(0.3, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.7, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.3, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.7, bpm)
keypress("z", x, bpm)
rest(0.3, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.11, bpm)
keypress("W", x, bpm)
rest(0.113, bpm)
keypress("t", x, bpm)
rest(0.11, bpm)
keypress("W", x, bpm)
rest(0.11, bpm)
keypress("t", x, bpm)
rest(0.112, bpm)
keypress("Y", x, bpm)
rest(0.11, bpm)
keypress("t", x, bpm)
rest(0.11, bpm)
keypress("Y", x, bpm)
rest(0.112, bpm)
keypress("o", x, bpm)
rest(0.11, bpm)
keypress("l", x, bpm)
rest(0.11, bpm)
keypress("Z", x, bpm)
rest(0.113, bpm)
keypress("v", x, bpm)
rest(0.11, bpm)
keypress("Z", x, bpm)
rest(0.11, bpm)
keypress("v", x, bpm)
rest(0.113, bpm)
keypress("B", x, bpm)
rest(0.11, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.075, bpm)
keypress("d", x, bpm)
rest(0.258, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.075, bpm)
keypress("p", x, bpm)
rest(0.258, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.075, bpm)
keypress("s", x, bpm)
rest(1.925, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
rest(0.075, bpm)
keypress("f", x, bpm)
rest(0.077, bpm)
keypress("D", x, bpm)
rest(0.848, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.033, bpm)
keypress("J", x, bpm)
rest(0.3, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.033, bpm)
keypress("f", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.11, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.113, bpm)
keypress("O", x, bpm)
rest(0.11, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.11, bpm)
keypress("O", x, bpm)
rest(0.112, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.11, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.033, bpm)
keypress("H", x, bpm)
rest(0.3, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
rest(0.11, bpm)
keypress("J", x, bpm)
rest(0.113, bpm)
keypress("H", x, bpm)
rest(0.11, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
rest(0.11, bpm)
keypress("H", x, bpm)
rest(0.113, bpm)
keypress("J", x, bpm)
rest(0.11, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.054, bpm)
keypress("J", x, bpm)
rest(0.056, bpm)
keypress("k", x, bpm)
rest(0.223, bpm)
keypress("J", x, bpm)
keypress("W", x, bpm)
rest(0.11, bpm)
keypress("H", x, bpm)
rest(0.112, bpm)
keypress("g", x, bpm)
rest(0.11, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.11, bpm)
keypress("H", x, bpm)
rest(0.113, bpm)
keypress("g", x, bpm)
rest(0.11, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.7, bpm)
keypress("P", x, bpm)
rest(0.3, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.075, bpm)
keypress("s", x, bpm)
rest(0.258, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.033, bpm)
keypress("D", x, bpm)
rest(0.3, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("W", x, bpm)
rest(0.033, bpm)
keypress("g", x, bpm)
rest(0.3, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1.7, bpm)
keypress("c", x, bpm)
rest(0.3, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
rest(2, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("$", x, bpm)
rest(0.7, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.3, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
rest(0.7, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(1.223, bpm)
keypress("D", x, bpm)
rest(0.11, bpm)
keypress("g", x, bpm)
rest(0.11, bpm)
keypress("D", x, bpm)
rest(0.113, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.11, bpm)
keypress("s", x, bpm)
rest(0.11, bpm)
keypress("P", x, bpm)
rest(0.112, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.11, bpm)
keypress("s", x, bpm)
rest(0.11, bpm)
keypress("P", x, bpm)
rest(0.112, bpm)
keypress("i", x, bpm)
rest(1.11, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(0.075, bpm)
keypress("l", x, bpm)
rest(1.258, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("l", x, bpm)
keypress("m", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("Z", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.075, bpm)
keypress("g", x, bpm)
rest(0.258, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("V", x, bpm)
rest(0.333, bpm)
keypress("B", x, bpm)
rest(0.333, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("Z", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("B", x, bpm)
rest(0.333, bpm)
keypress("V", x, bpm)
rest(0.333, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.367, bpm)
keypress("V", x, bpm)
rest(0.3, bpm)
keypress("c", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.033, bpm)
keypress("x", x, bpm)
rest(0.3, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.11, bpm)
keypress("P", x, bpm)
rest(0.112, bpm)
keypress("s", x, bpm)
rest(0.11, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.833, bpm)
keypress("Z", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("L", x, bpm)
rest(0.167, bpm)
keypress("Z", x, bpm)
keypress("8", x, bpm)
rest(0.167, bpm)
keypress("c", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
keypress("(", x, bpm)
rest(0.89, bpm)
keypress("s", x, bpm)
rest(0.11, bpm)
keypress("S", x, bpm)
rest(0.11, bpm)
keypress("D", x, bpm)
rest(0.112, bpm)
keypress("S", x, bpm)
rest(0.11, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1.033, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(2.3, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("s", x, bpm)
rest(0.075, bpm)
keypress("D", x, bpm)
rest(0.075, bpm)
keypress("g", x, bpm)
rest(0.079, bpm)
keypress("h", x, bpm)
rest(1.771, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.667, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.333, bpm)
keypress("l", x, bpm)
rest(0.333, bpm)
keypress("Z", x, bpm)
rest(0.333, bpm)
keypress("c", x, bpm)
rest(0.075, bpm)
keypress("v", x, bpm)
rest(0.075, bpm)
keypress("B", x, bpm)
rest(0.079, bpm)
keypress("v", x, bpm)
rest(1.771, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("v", x, bpm)
rest(1.333, bpm)
keypress("c", x, bpm)
rest(0.667, bpm)
keypress("c", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("l", x, bpm)
rest(0.667, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.167, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.167, bpm)
keypress("z", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("x", x, bpm)
keypress("q", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.167, bpm)
keypress("b", x, bpm)
rest(0.167, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("Z", x, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.11, bpm)
keypress("W", x, bpm)
rest(0.113, bpm)
keypress("t", x, bpm)
rest(0.11, bpm)
keypress("W", x, bpm)
rest(0.11, bpm)
keypress("t", x, bpm)
rest(0.112, bpm)
keypress("Y", x, bpm)
rest(0.11, bpm)
keypress("t", x, bpm)
rest(0.11, bpm)
keypress("Y", x, bpm)
rest(0.112, bpm)
keypress("o", x, bpm)
rest(0.11, bpm)
keypress("l", x, bpm)
rest(0.11, bpm)
keypress("Z", x, bpm)
rest(0.113, bpm)
keypress("v", x, bpm)
rest(0.11, bpm)
keypress("Z", x, bpm)
rest(0.11, bpm)
keypress("v", x, bpm)
rest(0.112, bpm)
keypress("B", x, bpm)
rest(0.11, bpm)
keypress("v", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.075, bpm)
keypress("d", x, bpm)
rest(0.258, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.075, bpm)
keypress("p", x, bpm)
rest(0.258, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.075, bpm)
keypress("s", x, bpm)
rest(1.925, bpm)
keypress("c", x, bpm)
keypress("$", x, bpm)
rest(0.077, bpm)
keypress("^", x, bpm)
rest(0.077, bpm)
keypress("*", x, bpm)
rest(0.081, bpm)
keypress("q", x, bpm)
rest(1.765, bpm)
keypress("Z", x, bpm)
keypress("$", x, bpm)
rest(0.077, bpm)
keypress("^", x, bpm)
rest(0.077, bpm)
keypress("*", x, bpm)
rest(0.081, bpm)
keypress("(", x, bpm)
rest(1.765, bpm)
keypress("c", x, bpm)
keypress("$", x, bpm)
rest(0.077, bpm)
keypress("^", x, bpm)
rest(0.077, bpm)
keypress("*", x, bpm)
rest(0.081, bpm)
keypress("q", x, bpm)
rest(0.465, bpm)
keypress("B", x, bpm)
rest(0.3, bpm)
keypress("c", x, bpm)
rest(0.7, bpm)
keypress("x", x, bpm)
rest(0.3, bpm)
keypress("Z", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Z", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
rest(0.333, bpm)
keypress("c", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.075, bpm)
keypress("J", x, bpm)
rest(0.002, bpm)
keypress("4", x, bpm)
rest(0.075, bpm)
keypress("l", x, bpm)
rest(0.002, bpm)
keypress("8", x, bpm)
rest(0.075, bpm)
keypress("J", x, bpm)
rest(1.271, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("Z", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("!", x, bpm)
rest(0.077, bpm)
keypress("4", x, bpm)
rest(0.077, bpm)
keypress("8", x, bpm)
rest(0.546, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
rest(0.8, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("Z", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
keypress("!", x, bpm)
rest(0.075, bpm)
keypress("4", x, bpm)
rest(0.079, bpm)
keypress("8", x, bpm)
rest(0.096, bpm)
keypress("H", x, bpm)
rest(0.075, bpm)
keypress("J", x, bpm)
rest(0.175, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.833, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(1.333, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("V", x, bpm)
keypress("Q", x, bpm)
rest(0.075, bpm)
keypress("V", x, bpm)
rest(0.075, bpm)
keypress("m", x, bpm)
rest(0.077, bpm)
keypress("L", x, bpm)
rest(0.079, bpm)
keypress("Z", x, bpm)
rest(0.392, bpm)
keypress("I", x, bpm)
rest(0.635, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.698, bpm)
keypress("i", x, bpm)
rest(0.635, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.075, bpm)
keypress("P", x, bpm)
rest(0.077, bpm)
keypress("s", x, bpm)
rest(0.077, bpm)
keypress("P", x, bpm)
rest(0.469, bpm)
keypress("T", x, bpm)
rest(1.302, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
keypress("V", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.033, bpm)
keypress("B", x, bpm)
rest(0.133, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
keypress("c", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.033, bpm)
keypress("V", x, bpm)
rest(0.133, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.033, bpm)
keypress("c", x, bpm)
rest(0.133, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)

finishedSong()